Added Widget and Intents support and updated CI
Radar-STATS/Radar-STATS-iOS pull request #2
Opened 2020-10-07 16:51 UTC by pvieito

2020-10-07 17:41 UTC, pvieito commented
@jorgej-ramos Hi, the CI should now be working properly for PRs and pushes to `develop`! 😄

2020-10-08 03:43 UTC, jorgej-ramos requested changes
Overall it's a great job. Congratulations.

You simply need to follow the general coding styles rules that, although it's true that they are not documented, you can find examples throughout the project.

All annotations are easy to correct.

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/GetMetricsSummaryIntent+Additions.swift
> +            Calendar.current.dateComponents([.year, .month, .day, .hour, .minute], from: results.extractionDate)
I think there is an unnecessary line break here.

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/GetMetricsSummaryIntentHandler.swift
> +        catch {
The general style of the project avoids two lines for cases like this or "else" after "if". A single line provides vertical readability.

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/GetMetricsSummaryIntentHandler.swift
> +                .failureWithErrorDescription(error.localizedDescription)
In the same way as in the previous case, a line is preferable.
I even suggest:
`completion (.failureWithErrorDescription (error.localizedDescription))`
To avoid even more unnecessary code.

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/IntentHandlerProvider.swift
> +        }
Following the general line of the project, one line is preferable to three, in the case of "guard" with a simple return like this case.

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/IntentMetricsSummary+Additions.swift
> +        IntentHandlerProvider.localizedString("INTENTS_METRICS_SUMMARY_DISPLAY_NAME")
Another unnecessary line break

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/IntentMetricsSummary+Additions.swift
> +        }
This "guard" can be better expressed in one line

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/IntentMetricsSummary+Additions.swift
> +        IntentHandlerProvider.localizedString("INTENTS_UNKNOWN_DISPLAY_STRING")
Another unnecessary line break

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/IntentMetricsSummary+Additions.swift
> +        }
This "guard" can be better expressed in one line

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/IntentMetricsSummary+Additions.swift
> +        }
This "guard" can be better expressed in one line

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/IntentMetricsSummary+Additions.swift
> +        }
This "guard" can be better expressed in one line

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/IntentMetricsSummary+Additions.swift
> +        }
This "guard" can be better expressed in one line

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/IntentMetricsSummary+Additions.swift
> +        }
This "guard" can be better expressed in one line

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSWidgetExtension/Assets.xcassets/WidgetGradientBottomColor.colorset/Contents.json
> +}
To create interchangeable assets, I usually prefer to create an asset file for colors and another for images. At this moment we may have few colors and images, but at the architectural level and at the collaborative level with designers it is interesting to divide it.

Don't change it now, but we'll refactor it later.

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSWidgetExtension/MetricsSummaryWidget.swift
> +        MetricsSummaryEntry(configuration: GetMetricsSummaryIntent())
Following the same pattern of a few lines below, I propose the following:
```suggestion
        let configuration = GetMetricsSummaryIntent()
        MetricsSummaryEntry(configuration: configuration)
```

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSWidgetExtension/MetricsSummaryWidget.swift
> +            configuration: configuration, loadResults: true)
Another unnecessary line break

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSWidgetExtension/MetricsSummaryWidget.swift
> +        else {
The general style of the project avoids two lines for cases like this. A single line provides vertical readability.

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSWidgetExtension/MetricsSummaryWidget.swift
> +            entry: MetricsSummaryEntry(configuration: GetMetricsSummaryIntent()))
Unnecessary line break

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSWidgetExtension/WidgetExtension.swift
> +}
Maybe it will be great to have a preview here using a `PreviewProvider`

2020-10-08 03:43 UTC, jorgej-ramos commented on RadarSTATSIntents/IntentHandlerProvider.swift
> +            return GetMetricsSummaryIntentHandler()
Suggestion: 

As a general rule, I try not to use get prefixes for method, class or struct names.
The reason is that if a method returns something, the signature itself is already telling you that something is obtained, with what in my view the prefix get is unnecessary.
As for classes and structs, I think the use of the get prefix is wrong in all cases. Even in Intent classes like these, it would avoid the use of prefixes: the word Intent itself implies obtaining information.

2020-10-08 12:32 UTC, pvieito commented on RadarSTATSIntents/IntentHandlerProvider.swift
> +            return GetMetricsSummaryIntentHandler()
All `INIntent` subclasses have a verb prefix which indicates the action of the intent which is linked to category action of the Intent Definition file.

You can find multiple examples of Apple using both the `get` and `set` prefix on their Intent classes like [`INGetReservationDetailsIntent`](https://developer.apple.com/documentation/sirikit/ingetreservationdetailsintent) or [`INSetTaskAttributeIntentResponse`](https://developer.apple.com/documentation/sirikit/insettaskattributeintentresponse).

2020-10-08 12:33 UTC, pvieito commented on RadarSTATSWidgetExtension/WidgetExtension.swift
> +}
This is a `WidgetBundle`, so there should already be previews in each `Widget`.

2020-10-15 05:10 UTC, merged